s = open('24.txt').readline()
# while 'AAA' in s: s = s.replace('AAA', 'AA AA')
# while 'BBB' in s: s = s.replace('BB', 'BB BB')
# while 'CCC' in s: s = s.replace('CCC', 'CC CC')
# s = s.replace('AAA', 'AA AA')
# s = s.replace('BB', 'BB BB')
# s = s.replace('CCC', 'CC CC')
s = s.replace('AA', 'A A').replace('BB', 'B B').replace('CC', 'C C')
print(max(len(x) for x in s.split()))
print(s.count('AAA'))
# print(max([x for x in s.split()]))